name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  test:
    name: Test Application
    runs-on: self-hosted # Ensure your Windows self-hosted runner is online and labeled "self-hosted"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests and capture results
        run: |
          npm install
          npm test > test-result.txt || echo "Tests failed"
        shell: pwsh # Use pwsh for Windows shell

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: test-result.txt

  deploy:
    name: Deploy to Self-Hosted Runner
    needs: test
    runs-on: self-hosted

    steps:
      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-result
          path: downloaded-artifacts

      - name: Display downloaded test results
        run: type downloaded-artifacts/test-result.txt # Use `type` instead of `cat` on Windows
        shell: pwsh

      - name: Checkout repository for deployment
        uses: actions/checkout@v4

      - name: Set up Node.js on self-hosted runner
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Stop existing application
        run: |
          if (Get-Command pm2 -ErrorAction SilentlyContinue) {
            pm2 stop all
            pm2 delete all
          } else {
            Write-Host "PM2 not found. Manual stop/start might be needed."
            taskkill /IM node.exe /F
          }
        shell: pwsh # Correct shell for Windows PowerShell Core

      - name: Start Node.js application with PM2
        run: |
          # npm install -g pm2 # Uncomment if PM2 is not installed globally
          pm2 start server.js --name "node-app"
          pm2 save
        shell: pwsh